### PR TITLE
Fix icon vanishing problem while moving multiple players

### LINKED ISSUE #34: Icon vanishing problem while moving multiple players
Hello, I implemented "off limits" map and tested it, but when I move player after rule 'wall is you' is created, some walls are vanishing (shown in gif). I think there is problem when walls are overlaped.

ezgif com-gif-maker
.

### PR DESCRIPTION
**Pull request by utilForever**
This revision includes:
- Fix icon vanishing problem while moving multiple players (Resolves #34)
  - Add map data for testing icon vanishing problem
  - Add resources for new map data
  - Replace the type of 'm_types' with 'std::map'
  - Add unit test for checking icon vanishing problem

### CODE REVIEW

**Comment by utilForever** [comment]
@lssac7778 Can you check this PR? Thanks.

**Comment by lssac7778** [comment]
Good! The problem resolved.

**Comment by lssac7778** [comment]
However, there is other problem while moving multiple players. In 'off limits' maps, game is not win when reach flag with multiple players. Also, The wall doesn't disapper when it overlaped with skull. Should I make new issue for this problem?
bug2

**Comment by utilForever** [comment]
@Issac7778 Oh... Can you add this problem as an issue? Thanks.

**Pull request merged**
